server.port=8083

server.error.include-message=always

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://eusouprogramadorjava.cpyr2hk5gjg9.us-east-1.rds.amazonaws.com:3306/eusouprogramadorjava
spring.datasource.username=admin
spring.datasource.password=8888741520
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect
spring.jpa.show-sql: true

